import {useEffect,useMemo,useState} from "react";
import {supabase} from "../supabase";

const money=v=>v===null||v===undefined?"-":new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP",maximumFractionDigits:0}).format(Number(v));
const dt=v=>!v?"-":new Date(v).toLocaleString("en-PH",{timeZone:"Asia/Manila",month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",hour12:true});
function Status({value}){const s=String(value||"").toUpperCase();let c="status-badge ";c+=s==="ACTIVE"?"status-active":s==="COMPLETED_WITH_WINNER"?"status-success":s==="CLOSED_NO_WINNER"?"status-muted":s==="AWAITING_FINALIZER"?"status-warning":"";return <span className={c}>{s.replaceAll("_"," ")}</span>}
function Card({title,value,sub,onClick}){return <button className="metric-card" onClick={onClick}><span>{title}</span><strong>{value}</strong><small>{sub}</small></button>}
function Row({label,value}){return <div className="detail-row"><span>{label}</span><strong>{value}</strong></div>}

export default function PortalPage({session}){
 const [client,setClient]=useState(null),[auctions,setAuctions]=useState([]),[page,setPage]=useState("dashboard"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[filter,setFilter]=useState("ALL"),[search,setSearch]=useState(""),[detail,setDetail]=useState(null),[bids,setBids]=useState([]),[detailLoading,setDetailLoading]=useState(false);
 useEffect(()=>{load()},[]);
 async function load(){setLoading(true);setError("");try{const {data:cu,error:e1}=await supabase.from("client_users").select("client_id,role,status").eq("user_id",session.user.id).eq("status","ACTIVE").maybeSingle();if(e1)throw e1;if(!cu)throw new Error("Your login is not mapped to an active client.");const {data:mc,error:e2}=await supabase.from("master_clients").select("client_id,name,status,created_at").eq("client_id",cu.client_id).maybeSingle();if(e2)throw e2;setClient({...mc,role:cu.role});const {data:a,error:e3}=await supabase.from("client_auction_list").select("*").order("post_created_at",{ascending:false});if(e3)throw e3;setAuctions(a||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function openAuction(id){setPage("detail");setDetailLoading(true);setDetail(null);setBids([]);try{const {data:d,error:e1}=await supabase.from("client_auction_detail").select("*").eq("auction_item_id",id).maybeSingle();if(e1)throw e1;const {data:b,error:e2}=await supabase.from("client_auction_bid_history").select("*").eq("auction_item_id",id).order("commented_at",{ascending:false});if(e2)throw e2;setDetail(d);setBids(b||[])}catch(e){setError(e.message)}finally{setDetailLoading(false)}}
 const metrics=useMemo(()=>({active:auctions.filter(a=>a.ui_status==="ACTIVE").length,completed:auctions.filter(a=>a.ui_status==="COMPLETED_WITH_WINNER").length,noWinner:auctions.filter(a=>a.ui_status==="CLOSED_NO_WINNER").length,pending:auctions.filter(a=>String(a.payment_status||"").toLowerCase()==="pending").length,total:auctions.reduce((n,a)=>n+Number(a.winning_amt||0),0)}),[auctions]);
 const shown=useMemo(()=>auctions.filter(a=>(filter==="ALL"||a.ui_status===filter)&&(!search.trim()||[a.item_label,a.highest_bidder_name,a.fb_post_id,a.payment_status].filter(Boolean).join(" ").toLowerCase().includes(search.trim().toLowerCase()))),[auctions,filter,search]);
 function goAuctions(f="ALL"){setFilter(f);setSearch("");setPage("auctions")}
 if(loading)return <div className="loading-screen"><div className="loading-card"><h2>Loading dashboard</h2><p>Retrieving auction data...</p></div></div>;
 return <div className="app-shell">
  <aside className="sidebar"><div className="sidebar-brand"><div className="brand-logo small">A</div><div><strong>Auction Automation</strong><span>Client Portal</span></div></div><nav><button className={page==="dashboard"?"active":""} onClick={()=>setPage("dashboard")}>Dashboard</button><button className={page!=="dashboard"?"active":""} onClick={()=>goAuctions()}>Auctions</button><button disabled>Payments</button><button disabled>Facebook</button><button disabled>Reports</button></nav><div className="sidebar-footer"><strong>{client?.name||session.user.email}</strong><span>{client?.role||"CLIENT"}</span><button onClick={()=>supabase.auth.signOut()}>Sign out</button></div></aside>
  <main className="dashboard-content">{error&&<div className="dashboard-error">{error}</div>}
   {page==="dashboard"&&<><header className="dashboard-header"><div><p className="eyebrow">CLIENT DASHBOARD</p><h1>Welcome, {client?.name}</h1><p>Monitor auctions, winners and payments.</p></div><button className="secondary-button" onClick={load}>Refresh</button></header><section className="metrics-grid"><Card title="Active auctions" value={metrics.active} sub="Click to view" onClick={()=>goAuctions("ACTIVE")}/><Card title="Completed" value={metrics.completed} sub="With winner" onClick={()=>goAuctions("COMPLETED_WITH_WINNER")}/><Card title="No winner" value={metrics.noWinner} sub="Closed auctions" onClick={()=>goAuctions("CLOSED_NO_WINNER")}/><Card title="Pending payments" value={metrics.pending} sub="Awaiting payment" onClick={()=>{setFilter("ALL");setSearch("pending");setPage("auctions")}}/><Card title="Winning value" value={money(metrics.total)} sub="Total winning amount" onClick={()=>goAuctions("COMPLETED_WITH_WINNER")}/></section><AuctionTable rows={auctions.slice(0,10)} openAuction={openAuction} title="Recent auctions" subtitle="Click any row to open details."/></>}
   {page==="auctions"&&<><header className="dashboard-header"><div><p className="eyebrow">AUCTION MANAGEMENT</p><h1>Auctions</h1><p>Search, filter and inspect auction activity.</p></div><button className="secondary-button" onClick={load}>Refresh</button></header><section className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search item, bidder, post or payment..."/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">All statuses</option><option value="ACTIVE">Active</option><option value="COMPLETED_WITH_WINNER">Completed with winner</option><option value="CLOSED_NO_WINNER">Closed no winner</option><option value="AWAITING_FINALIZER">Awaiting finalizer</option></select></section><AuctionTable rows={shown} openAuction={openAuction} title="Auction list" subtitle={`${shown.length} matching record(s)`}/></>}
   {page==="detail"&&<><button className="back-button" onClick={()=>setPage("auctions")}>← Back to auctions</button>{detailLoading?<div className="loading-card"><h2>Loading auction...</h2></div>:detail?<><header className="dashboard-header"><div><p className="eyebrow">AUCTION DETAIL</p><h1>{detail.item_label}</h1><p>Facebook post: {detail.fb_post_id}</p></div><Status value={detail.ui_status}/></header><section className="detail-grid"><div className="detail-card"><h2>Auction rules</h2><Row label="Minimum bid" value={money(detail.min_bid)}/><Row label="Increment" value={money(detail.bid_increment)}/><Row label="Minimum bidders" value={detail.min_bidder_count}/><Row label="Buyout" value={money(detail.bid_buyout_amt)}/><Row label="Buyout until" value={dt(detail.buyout_dt_limit)}/><Row label="Auction ends" value={dt(detail.auction_end_dt)}/><Row label="Anti-sniper" value={`${detail.anti_sniper_minutes||0} minute(s)`}/></div><div className="detail-card"><h2>Current result</h2><Row label="Highest bid" value={money(detail.highest_bid)}/><Row label="Highest bidder" value={detail.highest_bidder_name||"-"}/><Row label="Valid bidders" value={detail.valid_bidder_count}/><Row label="Valid bids" value={detail.valid_bid_count}/><Row label="Invalid bids" value={detail.invalid_bid_count}/><Row label="Winner amount" value={money(detail.winning_amt)}/><Row label="Winner status" value={detail.winner_status||"-"}/></div><div className="detail-card"><h2>Payment</h2><Row label="Status" value={detail.payment_status||"-"}/><Row label="Amount" value={money(detail.payment_amount)}/><Row label="Winner declared" value={dt(detail.won_at)}/><Row label="Payment ID" value={detail.payment_id||"-"}/></div></section><section className="detail-card caption"><h2>Original auction caption</h2><pre>{detail.caption}</pre></section><BidTable rows={bids}/></>:<div className="empty-state">Auction not found.</div>}</>}
  </main>
 </div>
}

function AuctionTable({rows,openAuction,title,subtitle}){return <section className="panel"><div className="panel-header"><div><h2>{title}</h2><p>{subtitle}</p></div><span>{rows.length} records</span></div><div className="table-wrapper"><table><thead><tr><th>Item</th><th>Status</th><th>Highest bid</th><th>Bidder</th><th>Valid bidders</th><th>Valid/Invalid</th><th>Ends</th><th>Payment</th></tr></thead><tbody>{rows.map(a=><tr key={a.auction_item_id} className="clickable-row" onClick={()=>openAuction(a.auction_item_id)}><td><strong>{a.item_label}</strong><small>{a.fb_post_id}</small></td><td><Status value={a.ui_status}/></td><td>{money(a.highest_bid)}</td><td>{a.highest_bidder_name||"-"}</td><td>{a.valid_bidder_count}/{a.min_bidder_count}</td><td>{a.valid_bid_count}/{a.invalid_bid_count}</td><td>{dt(a.auction_end_dt)}</td><td>{a.payment_status||"-"}</td></tr>)}</tbody></table></div></section>}
function BidTable({rows}){return <section className="panel"><div className="panel-header"><div><h2>Bid history</h2><p>Captured comments and validation remarks.</p></div><span>{rows.length} bids</span></div><div className="table-wrapper"><table><thead><tr><th>Bidder</th><th>Comment</th><th>Bid amount</th><th>Validation</th><th>Reason</th><th>Commented at</th></tr></thead><tbody>{rows.map(b=><tr key={b.bid_id}><td>{b.fb_user_name||"-"}</td><td>{b.comment_text||"-"}</td><td>{money(b.bid_amt)}</td><td><span className={`status-badge ${b.is_valid?"status-active":"status-danger"}`}>{b.is_valid?"VALID":"INVALID"}</span></td><td>{b.invalid_reason||"-"}</td><td>{dt(b.commented_at)}</td></tr>)}</tbody></table></div></section>}
