import { useEffect, useMemo, useState } from "react";
import { supabase } from "../supabase";
export default function PreorderAdminPage({client}){
 const [posts,setPosts]=useState([]),[entries,setEntries]=useState([]),[templates,setTemplates]=useState([]),[selected,setSelected]=useState(null),[message,setMessage]=useState("");
 async function call(action,extra={}){const {data,error}=await supabase.functions.invoke("eo2mate",{headers:{"x-eo2mate-route":"preorder-admin"},body:{action,client_id:client.client_id,...extra}});if(error)throw error;if(!data?.success)throw new Error(data?.error||"Request failed");return data;}
 async function load(){try{const [p,t]=await Promise.all([call("LIST"),call("LIST_TEMPLATES")]);setPosts(p.posts||[]);setTemplates(t.templates||[]);}catch(e){setMessage(e.message)}}
 useEffect(()=>{if(client?.client_id)load()},[client?.client_id]);
 async function open(post){setSelected(post);const d=await call("ENTRIES",{post_id:post.post_id});setEntries(d.entries||[])}
 async function cancel(entry){const reason=window.prompt("Cancellation reason code (BUYER_REQUESTED, NO_PAYMENT, DUMMY_FAKE_SUSPECTED, NUISANCE_FAKE_ACTIVITY, OTHER):","BUYER_REQUESTED");if(!reason)return;await call("CANCEL_ENTRY",{post_entry_id:entry.post_entry_id,reason_code:reason});await open(selected);setMessage("Reservation cancelled and quantity released.")}
 const effective=useMemo(()=>{const map=new Map();for(const t of templates.filter(x=>x.client_id==null))map.set(`${t.event_code}|${t.channel_code}`,t);for(const t of templates.filter(x=>x.client_id!=null))map.set(`${t.event_code}|${t.channel_code}`,t);return [...map.values()]},[templates]);
 async function editTemplate(t){const text=window.prompt(`Message for ${t.event_code}`,t.message_text);if(text==null)return;await call("SAVE_TEMPLATE",{event_code:t.event_code,channel_code:t.channel_code,message_text:text,is_active:t.is_active});await load();setMessage("Message template saved.")}
 return <section className="post-hub"><header className="dashboard-header"><div><p className="eyebrow">SELLING · PRE-ORDER</p><h1>Pre-Order Management</h1><p>Monitor Single and Multiple Pre-Orders, reservations, closure status, reminders and automated messages.</p></div><button className="secondary-button" onClick={load}>Refresh</button></header>{message&&<div className="success-message">{message}</div>}
 <div className="dashboard-panel"><h2>Posts</h2><div className="table-wrap"><table><thead><tr><th>Type</th><th>Status</th><th>Deadline</th><th>Closure</th><th>Items</th><th></th></tr></thead><tbody>{posts.map(p=><tr key={p.post_id}><td>{p.post_type_code}</td><td>{p.status}</td><td>{p.ends_at?new Date(p.ends_at).toLocaleString():"—"}</td><td>{p.eo2mate_preorder_settings?.ordering_close_reason||"—"}</td><td>{p.eo2mate_post_items?.length||0}</td><td><button onClick={()=>open(p)}>View</button></td></tr>)}</tbody></table></div></div>
 {selected&&<div className="dashboard-panel"><h2>Reservations · {selected.post_type_code}</h2><p>{selected.caption}</p><div className="table-wrap"><table><thead><tr><th>Buyer</th><th>Status</th><th>Requested</th><th>Accepted</th><th>Required DP</th><th></th></tr></thead><tbody>{entries.map(e=><tr key={e.post_entry_id}><td>{e.fb_user_name||e.fb_user_id||"—"}</td><td>{e.status}</td><td>{e.requested_quantity}</td><td>{e.accepted_quantity}</td><td>{e.required_down_payment_amount??"—"}</td><td>{!['CANCELLED','REJECTED'].includes(String(e.status).toUpperCase())&&<button onClick={()=>cancel(e)}>Cancel</button>}</td></tr>)}</tbody></table></div></div>}
 <div className="dashboard-panel"><h2>Automated Messages</h2><p>Client overrides take priority over EO2MATE defaults. Payment reminder delivery remains disabled until a payment-status source is selected.</p><div className="table-wrap"><table><thead><tr><th>Event</th><th>Channel</th><th>Message</th><th></th></tr></thead><tbody>{effective.map(t=><tr key={`${t.event_code}|${t.channel_code}`}><td>{t.event_code}</td><td>{t.channel_code}</td><td>{t.message_text}</td><td><button onClick={()=>editTemplate(t)}>Edit</button></td></tr>)}</tbody></table></div></div>
 </section>
}
