import { useEffect, useMemo, useRef, useState } from 'react';
import { supabase } from '../supabase';
import { upper, number, settled, inactive, money, date, uniquePayments, orderPayments, groupPayments, paidAmount, csvCell, filterOrders } from './salesModel';
import './SalesPage.css';
const defaults={search:'',channel:'ALL',status:'ALL',from:'',to:''};
function Icon({type}) { return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{type==='refresh'?<><path d="M20 5v6h-6M4 19v-6h6"/><path d="M6 8a7 7 0 0 1 12-1l2 4M4 13l2 4a7 7 0 0 0 12-1"/></>:type==='export'?<path d="M12 3v12m-4-4 4 4 4-4M4 16v5h16v-5"/>:type==='close'?<path d="m6 6 12 12M18 6 6 18"/>:<><path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></>}</svg>; }
function Badge({value}) { return <span className={`sales-badge ${settled({status:value})?'sales-paid':''}`}>{String(value||'Not recorded').replaceAll('_',' ')}</span>; }
function Metric({title,value,note}) { return <div className="metric-card"><span>{title}</span><strong>{value}</strong><small>{note}</small></div>; }
function Field({label,children}) { return <label className="sales-field"><span>{label}</span>{children}</label>; }
function Detail({label,value}) { return <div className="sales-detail-row"><span>{label}</span><strong>{value??'—'}</strong></div>; }
async function clientRows(table,clientId) { const rows=[]; for(let offset=0;;offset+=500) { const {data,error}=await supabase.from(table).select(table==='orders'?'*, auction_items(item_label)':'*').eq('client_id',clientId).order('created_at',{ascending:false}).order(table==='orders'?'order_id':'order_group_id').range(offset,offset+499); if(error) throw error; rows.push(...(data||[])); if((data||[]).length<500) return rows; } }
async function linkedPayments(column,ids) { const rows=[]; for(let i=0;i<ids.length;i+=100) { for(let offset=0;;offset+=500) { const {data,error}=await supabase.from('payments').select('*').in(column,ids.slice(i,i+100)).order('payment_id').range(offset,offset+499); if(error) throw error; rows.push(...(data||[])); if((data||[]).length<500) break; } } return rows; }
export default function SalesPage({client,orderLabels=[]}) {
 const [data,setData]=useState({orders:[],groups:[],payments:[]}); const [busy,setBusy]=useState(true); const [error,setError]=useState(''); const [tab,setTab]=useState('SUMMARY'); const [filters,setFilters]=useState(defaults); const [selected,setSelected]=useState(null); const [page,setPage]=useState(1); const generation=useRef(0),dialog=useRef(null),returnFocus=useRef(null);
 const labels=useMemo(()=>new Map(orderLabels.map(row=>[row.order_id,row.item_label])),[orderLabels]);
 async function load() { const request=++generation.current; setBusy(true);setError('');setSelected(null);setData({orders:[],groups:[],payments:[]}); try { if(!client?.client_id) throw new Error('A client workspace is required to load Sales.'); const [orders,groups]=await Promise.all([clientRows('orders',client.client_id),clientRows('order_groups',client.client_id)]); const [byOrder,byGroup]=await Promise.all([linkedPayments('order_id',orders.map(row=>row.order_id)),linkedPayments('order_group_id',groups.map(row=>row.order_group_id))]); if(request===generation.current) setData({orders,groups,payments:uniquePayments([...byOrder,...byGroup])}); } catch(err) { if(request===generation.current) setError(err.message||'Unable to load Sales.'); } finally { if(request===generation.current) setBusy(false); } }
 useEffect(()=>{load();return()=>{generation.current++;};},[client?.client_id]); useEffect(()=>setPage(1),[filters,tab]);
 useEffect(()=>{if(!selected)return; returnFocus.current=document.activeElement; const element=dialog.current;element?.showModal();return()=>{element?.close();returnFocus.current?.focus?.();};},[selected]);
 const rows=useMemo(()=>data.orders.map(row=>({...row,item_label:row.item_label||row.item_name_snapshot||row.auction_items?.item_label||labels.get(row.order_id)})),[data.orders,labels]); const invalidRange=filters.from&&filters.to&&filters.from>filters.to;
 const filtered=useMemo(()=>invalidRange?[]:filterOrders(rows,filters),[rows,filters,invalidRange]);const active=filtered.filter(row=>!inactive(row));const groups=data.groups.filter(group=>filtered.some(row=>row.order_group_id===group.order_group_id));const groupMap=new Map(data.groups.map(group=>[group.order_group_id,group]));
 const summary=[...new Set(active.map(row=>row.source_type||'UNSPECIFIED'))].map(channel=>{const list=active.filter(row=>(row.source_type||'UNSPECIFIED')===channel);return {channel,count:list.length,subtotal:list.reduce((n,row)=>n+number(row.subtotal),0),total:list.reduce((n,row)=>n+number(row.total_amount),0)};});
 const selectedPayments=selected?.kind==='group'?groupPayments(selected.row,data.payments):selected?orderPayments(selected.row,data.payments):[];
 const list=tab==='GROUPS'?groups:filtered;const totalPages=Math.max(1,Math.ceil(list.length/25));const currentPage=Math.min(page,totalPages);const display=list.slice((currentPage-1)*25,currentPage*25);
 function change(key,value) { setFilters(f=>({...f,[key]:value})); }
 function exportCSV() { const header=['Date (Manila)','Order','Channel','Buyer','Item','Subtotal','Total','Order status','Payment status','Order group'];const lines=filtered.map(row=>[date(row.created_at),row.order_number||row.order_id,row.source_type,row.buyer_name,row.item_label,row.subtotal,row.total_amount,row.order_status,row.payment_status,groupMap.get(row.order_group_id)?.group_number||row.order_group_id]); const url=URL.createObjectURL(new Blob(['\uFEFF'+[header,...lines].map(line=>line.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8;'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='EO2MATE-Sales.csv';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000); }
 return <div className="sales-workspace">
 <header className="dashboard-header"><div><p className="eyebrow">SALES MANAGEMENT</p><h1>Sales</h1><p>Review customer orders, payments and fulfillment across your selling channels.</p></div><div className="sales-actions"><button className="secondary-button sales-export" onClick={exportCSV} disabled={busy||!!error||!filtered.length}><Icon type="export"/>Export</button><button className="icon-button refresh-icon-button" title="Refresh Sales" aria-label="Refresh Sales" disabled={busy} onClick={load}><Icon type="refresh"/></button></div></header>
 {error&&<div className="error-message" role="alert">{error} <button className="secondary-button" onClick={load}>Retry</button></div>}
 <section className="toolbar-card sales-filters" aria-label="Sales filters"><Field label="Search"><input className="search-input" value={filters.search} onChange={e=>change('search',e.target.value)} placeholder="Order, buyer or item…"/></Field><Field label="Channel"><select className="filter-select" value={filters.channel} onChange={e=>change('channel',e.target.value)}><option value="ALL">All channels</option>{[...new Set(rows.map(row=>upper(row.source_type)).filter(Boolean))].sort().map(value=><option key={value} value={value}>{value.replaceAll('_',' ')}</option>)}</select></Field><Field label="Order status"><select className="filter-select" value={filters.status} onChange={e=>change('status',e.target.value)}><option value="ALL">All statuses</option>{[...new Set(rows.map(row=>upper(row.order_status)).filter(Boolean))].sort().map(value=><option key={value}>{value}</option>)}</select></Field><Field label="From (Manila)"><input type="date" value={filters.from} onChange={e=>change('from',e.target.value)}/></Field><Field label="To (Manila)"><input type="date" value={filters.to} onChange={e=>change('to',e.target.value)}/></Field><button className="secondary-button" onClick={()=>setFilters(defaults)}>Reset</button></section>
 {invalidRange&&<p role="alert" className="error-message">The end date must be on or after the start date.</p>}
 {busy?<div className="loading-card" role="status">Loading Sales…</div>:!error&&<>
 <section className="metrics-grid"><Metric title="Order subtotal" value={money(active.reduce((n,row)=>n+number(row.subtotal),0))} note="Active orders; recorded discounts included"/><Metric title="Order total" value={money(active.reduce((n,row)=>n+number(row.total_amount),0))} note="Including recorded shipping charges"/><Metric title="Transactions" value={filtered.length} note={`${active.length} active; ${filtered.length-active.length} cancelled / forfeited`}/><Metric title="Awaiting payment" value={active.filter(row=>['PENDING','PAYMENT_PENDING','PARTIALLY_PAID','UNPAID'].includes(upper(row.payment_status))).length} note="Orders by recorded payment status"/></section>
 <section className="dashboard-panel sales-tabs"><div role="tablist" aria-label="Sales sections" className="sales-actions">{[['SUMMARY','Summary'],['TRANSACTIONS','Transactions'],['GROUPS','Order groups']].map(([key,label])=><button key={key} role="tab" aria-selected={tab===key} aria-controls="sales-panel" className={tab===key?'primary-button':'secondary-button'} onClick={()=>setTab(key)}>{label}</button>)}</div></section>
 <section className="dashboard-panel" id="sales-panel" role="tabpanel"><div className="panel-header"><div><h2>{tab==='SUMMARY'?'Sales by channel':tab==='GROUPS'?'Order groups':'Sales transactions'}</h2><p>{tab==='GROUPS'?`${groups.length} groups linked to matching orders`:`${filtered.length} matching transactions`}</p></div></div>
 {tab==='SUMMARY'?<><div className="table-wrapper"><table><thead><tr><th>Channel</th><th>Transactions</th><th>Subtotal</th><th>Total</th></tr></thead><tbody>{summary.map(row=><tr key={row.channel}><td>{row.channel.replaceAll('_',' ')}</td><td>{row.count}</td><td>{money(row.subtotal)}</td><td>{money(row.total)}</td></tr>)}{!summary.length&&<tr><td colSpan="4" className="empty-table-cell">No active sales match these filters.</td></tr>}</tbody></table></div><div className="sales-payment-note"><strong>Recorded collections</strong><p>Standalone order payments: {money(paidAmount(filtered.flatMap(row=>orderPayments(row,data.payments))))} · Linked group payments: {money(paidAmount(groups.flatMap(group=>groupPayments(group,data.payments))))}</p><p>Group collections cover the entire group, including orders outside the filters. Group payments are not allocated to individual items or channels.</p></div></>:<><div className="table-wrapper"><table><thead>{tab==='GROUPS'?<tr><th>Group</th><th>Buyer</th><th>Total</th><th>Collected</th><th>Status</th><th>Action</th></tr>:<tr><th>Created</th><th>Order / group</th><th>Channel</th><th>Buyer / item</th><th>Total</th><th>Order</th><th>Payment</th><th>Action</th></tr>}</thead><tbody>{display.map(row=>tab==='GROUPS'?<tr key={row.order_group_id}><td>{row.group_number||row.order_group_id}</td><td>{row.buyer_name||'—'}</td><td>{money(row.total_amount)}</td><td>{money(paidAmount(groupPayments(row,data.payments)))}</td><td><Badge value={row.payment_status||row.group_status||row.status}/></td><td><button className="icon-button" title="View group" aria-label={`View group ${row.group_number||row.order_group_id}`} onClick={()=>setSelected({kind:'group',row})}><Icon/></button></td></tr>:<tr key={row.order_id}><td>{date(row.created_at)}</td><td>{row.order_number||row.order_id}<small className="sales-muted">{groupMap.get(row.order_group_id)?.group_number||(row.order_group_id?'Grouped order':'Standalone')}</small></td><td>{String(row.source_type||'Unspecified').replaceAll('_',' ')}</td><td>{row.buyer_name||'—'}<small className="sales-muted">{row.item_label||'Item details not supplied'}</small></td><td>{money(row.total_amount)}</td><td><Badge value={row.order_status}/></td><td><Badge value={row.payment_status}/></td><td><button className="icon-button" title="View sale" aria-label={`View sale ${row.order_number||row.order_id}`} onClick={()=>setSelected({kind:'order',row})}><Icon/></button></td></tr>)}{!display.length&&<tr><td colSpan={tab==='GROUPS'?6:8} className="empty-table-cell">No records match these filters.</td></tr>}</tbody></table></div><div className="sales-pagination"><span>Page {currentPage} of {totalPages}</span><div className="sales-actions"><button className="secondary-button" disabled={currentPage<=1} onClick={()=>setPage(currentPage-1)}>Previous</button><button className="secondary-button" disabled={currentPage>=totalPages} onClick={()=>setPage(currentPage+1)}>Next</button></div></div></>}
 </section></>}
 {selected&&<dialog ref={dialog} className="sales-dialog" aria-labelledby="sale-detail-title" onCancel={()=>setSelected(null)}><header className="panel-header"><div><p className="eyebrow">{selected.kind==='group'?'ORDER GROUP':'SALES TRANSACTION'}</p><h2 id="sale-detail-title">{selected.row.order_number||selected.row.group_number||selected.row.order_id||selected.row.order_group_id}</h2></div><button className="icon-button" aria-label="Close details" onClick={()=>setSelected(null)}><Icon type="close"/></button></header>
 <div className="detail-grid"><section className="detail-card"><h3>Order</h3><Detail label="Created" value={date(selected.row.created_at)}/><Detail label="Buyer" value={selected.row.buyer_name||'—'}/><Detail label="Item" value={selected.row.item_label||'—'}/><Detail label="SKU / variant" value={selected.row.sku||selected.row.item_code_snapshot||'—'}/><Detail label="Quantity" value={selected.row.quantity??selected.row.accepted_quantity??'—'}/><Detail label="Status" value={selected.row.order_status||selected.row.group_status||selected.row.status||'—'}/><Detail label="Fulfillment" value={selected.row.fulfillment_status||'Not recorded'}/></section><section className="detail-card"><h3>Amounts</h3><Detail label="Subtotal" value={selected.row.subtotal!=null?money(selected.row.subtotal):'—'}/><Detail label="Shipping" value={selected.row.shipping_fee!=null?money(selected.row.shipping_fee):'—'}/><Detail label="Total" value={money(selected.row.total_amount)}/><Detail label="Payment status" value={selected.row.payment_status||'Not recorded'}/><Detail label="Linked collections" value={money(paidAmount(selectedPayments))}/>{selected.kind==='order'&&selected.row.order_group_id&&<p>View the order group for its shared payment history.</p>}</section></div>
 {selected.kind==='group'&&<section><h3>Group orders</h3><div className="table-wrapper"><table><thead><tr><th>Order</th><th>Item</th><th>Total</th><th>Status</th></tr></thead><tbody>{rows.filter(row=>row.order_group_id===selected.row.order_group_id).map(row=><tr key={row.order_id}><td>{row.order_number||row.order_id}</td><td>{row.item_label||'—'}</td><td>{money(row.total_amount)}</td><td><Badge value={row.order_status}/></td></tr>)}</tbody></table></div></section>}
 <section><h3>Payment history</h3><div className="table-wrapper"><table><thead><tr><th>Date</th><th>Provider / reference</th><th>Amount</th><th>Status</th></tr></thead><tbody>{selectedPayments.map(row=><tr key={row.payment_id}><td>{date(row.paid_at||row.created_at)}</td><td>{row.provider||'—'}<small className="sales-muted">{row.payment_reference||row.request_reference_number||'—'}</small></td><td>{money(row.amount)}</td><td><Badge value={row.status||row.payment_status}/></td></tr>)}{!selectedPayments.length&&<tr><td colSpan="4">No directly linked payment records.</td></tr>}</tbody></table></div></section><footer className="sales-actions"><button className="secondary-button" onClick={()=>setSelected(null)}>Close</button></footer></dialog>}
 </div>;
}
